# Add your own transformation here with the use of Regex, like this:
#   UUID=[".*[U]uid"]
# Any column name matching that value, will have the type UUID.
# If you want to add a type with a package prefix, use the special FROMPACKAGE syntax, like so:
#   MyPackageFROMPACKAGEMyClass=["MyClass"]